### ISSUE TITLE
re.ChatGPT.revChatGPT module not found.

### ISSUE THREAD

**Issue by ikhana** [cwyrwas/ChatGPT-Content-Generator#3]
I installed` revCHatGPT` through pip but when I run the content generation file it gives me this error

`Traceback (most recent call last):
  File "C:\Users\Inaam\ChatGPT-Content-Generator\content_gen.py", line 4, in <module>
    from chat_gpt_interface import get_video_script, save_script
  File "C:\Users\Inaam\ChatGPT-Content-Generator\chat_gpt_interface.py", line 1, in <module>
    from revChatGPT.revChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'`

I guess the issue is just due to path, but do not know how to resolve this.

**Comment by ehsanpo** [comment]
I have same issue! running on osx.

**Comment by DaniSchober** [comment]
Try: from revChatGPT.ChatGPT import Chatbot

**Comment by ikhana** [comment]
> I installed` revCHatGPT` through pip but when I run the content generation file it gives me this error
> 
> `Traceback (most recent call last): File "C:\Users\Inaam\ChatGPT-Content-Generator\content_gen.py", line 4, in <module> from chat_gpt_interface import get_video_script, save_script File "C:\Users\Inaam\ChatGPT-Content-Generator\chat_gpt_interface.py", line 1, in <module> from revChatGPT.revChatGPT import Chatbot ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'`
> 
> I guess the issue is just due to path, but do not know how to resolve this.

IF you guys have not found the solution, here what I did 

pip`pip install --upgrade revChatGPT`

and a bit change in code 

`from revChatGPT.ChatGPT import Chatbot import os`
and 
`response = chatbot.ask(prompt,conversation_id=None, parent_id=None)`

    


    `
